### ISSUE TITLE
we should expose the Log URL on the Build status (or as an annotation for now)

### ISSUE THREAD

**Issue by jstrachan** [openshift/openshift-jenkins-sync-plugin#15]
so that one day the `oc logs build/foo` command can pull the logs from the URL.

**Comment by jstrachan** [comment]
kinda done - just need a field on BuildStatus we can use to store it directly in the build status

**Comment by bparees** [comment]
@jstrachan since the logs uri is exposed as an annotation on the build, should we consider this done?
