### ISSUE TITLE
allow configuration of more than one namespace to sync

### ISSUE THREAD

**Issue by bparees** [openshift/openshift-jenkins-sync-plugin#63]
The sync plugin currently looks at either the current namespace for jenkins, or a globally configured namespace, when scanning for buildconfigs to sync.  It would be be preferable to allow a list of namespaces to be configures and the sync plugin to sync all of them.

@jimmidyson if this is already possible, please let me know.

**Comment by jstrachan** [comment]
why does the slave namespace matter so much? Right now all Builds occur in the namespace of the BuildConfig too don't they?

If you want to run part of the build in a separate namespace you can use the [kubernetes workflow](https://github.com/fabric8io/kubernetes-workflow/blob/master/kubernetes-steps/readme.md#using-a-maven-kubernetes-pod) to run pods in any namespace you like (that the jenkins SA has access to)

**Comment by bparees** [comment]
Because I might want a single jenkins master that many users have access to and i might want their jobs to run in their respective namespaces either for resource reasons, or because i want the slave pods to have direct access to a particular namespace (by virtue of them running as a particular service account).

**Comment by bparees** [comment]
This issue should really be "i want the sync plugin to look at more than one namespace", the slave launching is not the responsibility of the sync plugin.  updating description.

**Comment by siamaksade** [comment]
Leaving the namespace blank supposedly syns with all namespaces but it's not possible due to a bug (logged separately):
https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/97

**Comment by bparees** [comment]
also tracked as bug https://bugzilla.redhat.com/show_bug.cgi?id=1391209

**Comment by jimmidyson** [comment]
From #97:

We can query `/oapi/v1/projects` to get the list of projects that are accessible & I guess we could watch that list to update what is projects have BCs synced. This will need multiple watchers per namespace for this which will increase memory/CPU requirements but should be manageable.

So this should handle either blank project (renamed from namespace to be in sync with OpenShift parlance) which will watch all accessible projects, or accept a list of projects to watch.

**Comment by bparees** [comment]
the "list of projects to watch" is definitely more critical than "watch all projects", in terms of implementation priority.

**Comment by jimmidyson** [comment]
Sure - it's the same either way tbh, the complexity is in managing the watchers & handling errors.

**Comment by bparees** [comment]
tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1390288
